version: "3.11"

networks:
  app:
    driver: bridge

volumes:
  postgres_data:
  backend_node_modules:
  frontend_node_modules:

services:
  postgres:
    image: postgres:16
    container_name: englishbytext_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - app

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    container_name: englishbytext_backend
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      NODE_ENV: development
      PORT: ${PORT:-4000}
      DATABASE_URL: ${DATABASE_URL}
      CHOKIDAR_USEPOLLING: "true"
    command: sh -c "npm run db:migrate && npm run db:seed && npm run dev"
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    ports:
      - "${PORT:-4000}:4000"
    networks:
      - app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    container_name: englishbytext_frontend
    env_file:
      - .env
    environment:
      VITE_DEV_SERVER_HOST: 0.0.0.0
      CHOKIDAR_USEPOLLING: "true"
    command: sh -c "npm ci || npm install && npm run dev -- --host 0.0.0.0 --port 5173"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "5173:5173"
    networks:
      - app

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: englishbytext_nginx
    depends_on:
      - frontend
      - backend
    ports:
      - "8080:80"
    networks:
      - app

  ngrok:
    image: ngrok/ngrok:latest
    container_name: englishbytext_ngrok
    depends_on:
      - frontend
    env_file:
      - .env
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    command: http --domain=${NGROK_DOMAIN:-wombat-accepted-whale.ngrok-free.app} http://frontend:5173
    ports:
      - "4040:4040" # ngrok web UI
    networks:
      - app
