apiVersion: v1
kind: PersistentVolume
metadata:
  name: piper-models-pv-linguatext
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /opt/local-path-provisioner/linguatext-piper-models

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: piper-models-pvc-linguatext
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: piper-models-pv-linguatext
  storageClassName: local-path
